/*
 This file is part of MetExploreViz 

 Copyright © 2016 INRA 
 Contact: http://metexplore.toulouse.inra.fr/metexploreViz/doc/contact 
 GNU General Public License Usage 
 This file may be used under the terms of the GNU General Public License version 3.0 as 
 published by the Free Software Foundation and appearing in the file LICENSE included in the 
 packaging of this file. 
 Please review the following information to ensure the GNU General Public License version 3.0 
 requirements will be met: http://www.gnu.org/copyleft/gpl.html. 
 If you are unsure which license is appropriate for your use, please contact us 
 at http://metexplore.toulouse.inra.fr/metexploreViz/doc/contact
 Version: 1.2.0.2 
 Build Date: Mon Nov 21 14:42:33 CET 2016 
 */
var NodeData=function(s,l,e,f,k,n,q,r,i,b,j,m,c,a,p,d,g,o,h){this.name=s;this.dbIdentifier=e;this.ec=f;this.id=k;this.identifier=d;this.reactionReversibility=n;this.isSideCompound=q;this.biologicalType=r;this.selected=i;this.duplicated=p;this.labelVisible=b;this.svg=j;this.svgWidth=m;this.svgHeight=c;if(g==undefined){this.pathways=[]}else{this.pathways=g}this.compartment=l;if(a==undefined){a=[]}this.mappingDatas=a;if(o==undefined){o=false}this.locked=o;this.label=h};NodeData.prototype={equals:function(a){var b=true;if(this.id!=a.id){b=false}return b},toString:function(){return this.id},isSelected:function(){return this.selected},setIsSelected:function(a){this.selected=a},isLocked:function(){return this.locked},setLocked:function(a){this.locked=a},isDuplicated:function(){return this.duplicated},setIsDuplicated:function(a){this.duplicated=a},getIsSideCompound:function(){return this.isSideCompound},setIsSideCompound:function(a){this.isSideCompound=a},getId:function(){return this.id},getIdentifier:function(){return this.identifier},getDbIdentifier:function(){return this.dbIdentifier},getBiologicalType:function(){return this.biologicalType},getLabelVisible:function(){return this.labelVisible},getReactionReversibility:function(){return this.reactionReversibility},setReactionReversibility:function(a){this.reactionReversibility=a},getName:function(){return this.name},setName:function(a){this.name=a},getLabel:function(){return this.label},setLabel:function(a){this.label=a},getId:function(){return this.id},getSvg:function(){return this.svg},getSvgHeight:function(){return this.svgHeight},getSvgWidth:function(){return this.svgWidth},getCompartment:function(){return this.compartment},getEC:function(){return this.ec},resetMapping:function(){this.mappingDatas=[]},addMappingData:function(a){this.mappingDatas.push(a)},removeMappingData:function(a){var b=[];this.mappingDatas.forEach(function(c){if(c.getMappingName()==a){b.push(c)}});b.forEach(function(d){var c=b.indexOf(d);if(c!=-1){b.splice(c,1)}})},getMappingDatasLength:function(){return this.mappingDatas.length},getMappingDatas:function(){return this.mappingDatas},getMappingDataByNameAndCond:function(a,b){var c=null;this.mappingDatas.forEach(function(d){if(d.getMappingName()==a&&d.getConditionName()==b){c=d}});return c},setMappingDataByNameAndCond:function(a,b,d){var c=null;this.mappingDatas.forEach(function(e){if(e.getMappingName()==a&&e.getConditionName()==b){c=e}});c.setMapValue(d)},getPathways:function(){return this.pathways},setPathways:function(a){this.pathways=a},addPathway:function(a){if(this.pathways.indexOf(a)==-1){this.pathways.push(a)}}};